apiVersion: v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/component: query-layer
    app.kubernetes.io/instance: benchmark-thanos-query
    app.kubernetes.io/name: thanos-query
    app.kubernetes.io/part-of: telemeter-benchmark
    app.kubernetes.io/version: v0.14.0
  name: benchmark-thanos-query
  namespace: telemeter-benchmark
spec:
  port:
    targetPort: web
  tls:
    insecureEdgeTerminationPolicy: Allow
    termination: edge
  to:
    kind: Service
    name: benchmark-thanos-query
