apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: query-layer
    app.kubernetes.io/instance: benchmark-thanos-query
    app.kubernetes.io/name: thanos-query
    app.kubernetes.io/part-of: telemeter-benchmark
    app.kubernetes.io/version: master-2020-02-13-adfef4b5
  name: benchmark-thanos-query
  namespace: telemeter-benchmark
spec:
  ports:
  - name: grpc
    port: 10901
    targetPort: grpc
  - name: http
    port: 9090
    targetPort: http
  selector:
    app.kubernetes.io/component: query-layer
    app.kubernetes.io/instance: benchmark-thanos-query
    app.kubernetes.io/name: thanos-query
    app.kubernetes.io/part-of: telemeter-benchmark
