apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: database-write-hashring
    app.kubernetes.io/instance: benchmark-thanos-receive-default
    app.kubernetes.io/name: thanos-receive
    app.kubernetes.io/part-of: telemeter-benchmark
    app.kubernetes.io/version: v0.14.0
    controller.receive.thanos.io/hashring: default
  name: benchmark-thanos-receive-default
  namespace: telemeter-benchmark
spec:
  clusterIP: None
  ports:
  - name: grpc
    port: 10901
    targetPort: 10901
  - name: http
    port: 10902
    targetPort: 10902
  - name: remote-write
    port: 19291
    targetPort: 19291
  selector:
    app.kubernetes.io/component: database-write-hashring
    app.kubernetes.io/instance: benchmark-thanos-receive-default
    app.kubernetes.io/name: thanos-receive
    app.kubernetes.io/part-of: telemeter-benchmark
    controller.receive.thanos.io/hashring: default
